[project]
name = "ollama-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.4.7",
    "pyperclip>=1.9.0",
    "pyqt6>=6.8.1",
    "pyside6==6.8.1",
]
